# Generated by Django 5.2 on 2025-04-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('popularity', models.FloatField()),
                ('is_explicit', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('social_media_users', models.BigIntegerField()),
                ('social_media_pct', models.FloatField()),
                ('total_population', models.BigIntegerField()),
                ('age_65_plus', models.FloatField()),
                ('age_25_64', models.FloatField()),
                ('age_15_24', models.FloatField()),
                ('age_5_14', models.FloatField()),
                ('age_0_4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('artists', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=10)),
                ('popularity', models.IntegerField()),
                ('is_explicit', models.BooleanField()),
                ('duration_ms', models.IntegerField()),
                ('album_name', models.CharField(max_length=200)),
                ('album_release_date', models.DateField(blank=True, null=True)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.IntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('time_signature', models.IntegerField()),
                ('country_full', models.CharField(max_length=50)),
            ],
        ),
    ]
