# Generated by Django 5.2 on 2025-04-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('spotify_id', 'country')},
        ),
    ]
