# Generated by Django 5.2 on 2025-04-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_song_country_alter_song_spotify_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('spotify_id', 'country_full')},
        ),
    ]
